openapi: 3.0.1
info:
  title: University Courses API
  description: API for retrieving university course information.
  version: "1.0"
servers:
  - url: PLUGIN_HOSTNAME
paths:
  /UoA/subjects:
    get:
      operationId: getSubjects
      summary: Get a list of all subjects
      responses:
        "200":
          description: A list of subjects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Subject"
  /UoA/courses/{subject}/{level}:
    get:
      operationId: getCourses
      summary: Get a list of all courses of a specific subject at a specific level
      parameters:
        - in: path
          name: subject
          schema:
            type: string
          required: true
          description: The subject of the courses. This parameter must be from the list of all subjects.
        - in: path
          name: level
          schema:
            type: string
          required: true
          description: The level of courses. (Undergraduate, Postgraduate Coursework)
      responses:
        "200":
          description: A list of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Course"
  /UoA/courses/{course_code}:
    get:
      operationId: getCourse
      summary: Get details of a specific course by course code
      parameters:
        - in: path
          name: course_code
          schema:
            type: string
          required: true
          description: The course code of the course. This parameter must be from the list of all course codes.
      responses:
        "200":
          description: Course details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Course"
        "404":
          description: Course not found
components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the course
        title:
          type: string
          description: The title of the course
        course_code:
          type: string
          description: The unique course code
        course_name:
          type: string
          description: The name of the course
        level:
          type: string
          description: The level of the course
        term:
          type: string
          description: The term of the course
        location:
          type: string
          description: The location of the course
        units:
          type: string
          description: The units of the course
        contact:
          type: string
          description: The contact hours of the course
        course_description:
          type: string
          description: The description of the course
        prerequisites:
          type: string
          description: The prerequisites of the course
        incompatible:
          type: string
          description: The incompatible courses of the course
        assumed_knowledge:
          type: string
          description: The assumed knowledge of the course
    Subject:
      type: object
      properties:
        name:
          type: string
          description: The unique name of the subject
