openapi: 3.0.1
info:
  title: University Courses API
  description: API for managing university courses, including retrieving and adding course information.
  version: "1.0"
servers:
  - url: http://172.30.76.166:5000
paths:
  /UoA/courses/{level}:
    get:
      operationId: getCourses
      summary: Get a list of all courses at a specific level
      responses:
        "200":
          description: A list of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'

  /UoA/courses/{course_code}:
    get:
      operationId: getCourse
      summary: Get details of a specific course by course code
      parameters:
        - in: path
          name: course_code
          schema:
            type: string
          required: true
          description: The course code of the course
      responses:
        "200":
          description: Course details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        "404":
          description: Course not found

components:
  schemas:
    Course:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the course
        title:
          type: string
          description: The title of the course
        course_code:
          type: string
          description: The unique course code
        course_name:
          type: string
          description: The name of the course
        level:
          type: string
          description: The level of the course
        term:
          type: string
          description: The term of the course
        location:
          type: string
          description: The location of the course
        units:
          type: string
          description: The units of the course
        contact:
          type: string
          description: The contact hours of the course
        course_description:
          type: string
          description: The description of the course
        prerequisites:
          type: string
          description: The prerequisites of the course
        incompatible:
          type: string
          description: The incompatible courses of the course
        assumed_knowledge:
          type: string
          description: The assumed knowledge of the course
